version: '2.4'

services:
  postgres:
    build:
      context: ./
      dockerfile: Dockerfile
    ports:
      - 5432:5432
    environment:
      - POSTGRES_HOST=postgres
      - POSTGRES_PORT=5432
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin
      - POSTGRES_DB=transactionapp
    volumes:
      - db-data:/var/lib/postgresql/data:rw
    healthcheck:
      test: pg_isready -U admin -h 127.0.0.1 -d transactionapp
volumes:
  db-data:
    driver: local
